[build] 
  publish = "dist"
  command = "npm run build"

[dev] 
  publish = "./dist"
  command = "npm run serve"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/.netlify/functions/cart-view"
  status = 200

